version: '3.8'

services:
  mariadb:
    container_name: mariadb
    # image: mariadb
    build: ./requirements/mariadb/
    image: custom-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    container_name: wordpress
    # image: wordpress
    build: ./requirements/wordpress/
    image: custom-wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    restart: always

  nginx:
    container_name: nginx
    # image: nginx
    build: ./requirements/nginx/
    image: custom-nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - mynetwork
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ssanei/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ssanei/data/mariadb
      o: bind

networks:
  mynetwork:
    # name: mynetwork
    driver: bridge
